version: '3.3'

services:
  nginx:
    container_name: articul-nginx
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - nodejs
  nodejs:
    entrypoint: [sh, -c, 'npm run dev']
    hostname: 'nodejs'
    container_name: articul-srv
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    links:
      - pgdb:pgdb
    volumes:
      - ./:/var/www/articul/
    depends_on:
      - pgdb
  pgdb:
    image: postgres:alpine
    container_name: articul-pgdb
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
